Login form
OlegElizarov/Kino-on_IOS pull request #1
Opened 2020-10-24 20:19 UTC by OlegElizarov

1. Инпуты для ввода логина и пароля
2. Кнопка для сабмита формы
3. Скрытие и проявление пароля по кнопке в инпуте пароля
4. Отображение сообщения при успешном логине(соответствие логина и пароля тестовым данным)

2020-10-25 12:57 UTC, OlegElizarov commented
1. Для каждого вида элементов создан свой отдельный класс
2. Расположения элементов задаются констрейнтами через код
3. Все создания элементов вынесены в отдельные конфигурационные функции

2020-10-31 15:24 UTC, blackplayerten requested changes
+ добавить линтер в проект, а то код стайл хромает

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +    var toggleButton:ToggleButton!
можно сразу создать объекты: let loginField = InputField()

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +    var Password:String
не var, а let

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +var testUser:User = User(Username: "testUser",Email: "test", Password: "123")
global var is evil 😈

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +        self.backgroundColor = UIColor.systemBlue
можно UIColor опустить

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +        createBorder()
можно объединить в один init с опциональной кнопкой по дефолту nil

2020-10-31 15:24 UTC, blackplayerten commented on TestApp/ViewController.swift
> +        ])
лучше писать:
```swift
profileLabel.topAnchor.constraint(equalTo: view.topAnchor,constant: 30).isActive = true
```
таким образом в каких-то кейсах можно изменить 1 из констреинтов

2020-11-21 11:52 UTC, closed without merging